// frontend-angular/src/app/components/navbar/navbar.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, Router, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { CartService } from '../../services/cart.service';
import { ThemeSwitcherComponent } from '../theme-switcher/theme-switcher.component';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, ThemeSwitcherComponent],
  templateUrl: './navbar.component.html'
})
export class NavbarComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);
  readonly cartService = inject(CartService);

  open = false;

  get user() {
    return this.auth.user;
  }

  get displayName(): string {
    const user = this.auth.user;
    if (!user) return '';
    const first = user.firstName || user.firstname;
    const last = user.lastName || user.lastname;
    const combined = [first, last].filter(Boolean).join(' ').trim();
    return combined || user.name || user.email?.split('@')[0] || '';
  }

  get cartCount(): number {
    return this.cartService.cartItems.reduce((sum, item) => sum + item.quantity, 0);
  }

  get links() {
    const base = [
      { to: '/', label: 'Home' },
      { to: '/menu', label: 'Menu' },
      { to: '/orders', label: 'My Orders' },
      { to: '/contact', label: 'Contact' }
    ];
    return this.user ? [...base, { to: '/account', label: 'Account' }] : base;
  }

  toggleOpen(): void {
    this.open = !this.open;
  }

  logout(): void {
    this.auth.logout();
    this.open = false;
    this.router.navigate(['/']);
  }
}

<header class="nav-surface sticky top-0 z-40 shadow-sm">
  <div class="mx-auto flex max-w-6xl items-center justify-between px-4 py-3">
    <a routerLink="/" class="flex items-center gap-3">
      <div class="flex h-10 w-10 items-center justify-center rounded-full bg-[var(--accent)] text-white shadow-lg">
        <span class="text-lg font-bold">CCD</span>
      </div>
      <span class="brand-title text-lg font-semibold text-primary sm:text-xl">Cafe Coffee Day</span>
    </a>

    <nav class="hidden items-center gap-6 text-sm font-semibold md:flex">
      <a
        *ngFor="let link of links"
        routerLink="{{ link.to }}"
        routerLinkActive="text-accent"
        class="text-secondary transition hover:text-accent"
      >
        {{ link.label }}
      </a>
      <a
        routerLink="/orders"
        class="relative inline-flex items-center gap-2 rounded-full border border-[var(--card-border)] bg-[var(--surface-layer)] px-3 py-1.5 text-xs font-semibold text-secondary transition hover:text-accent"
      >
        <span class="material-symbols-outlined text-sm">shopping_bag</span>
        Cart
        <span
          *ngIf="cartCount > 0"
          class="absolute -right-2 -top-2 flex h-5 w-5 items-center justify-center rounded-full bg-[var(--accent)] text-xs font-bold text-[var(--accent-contrast)] shadow"
        >
          {{ cartCount }}
        </span>
      </a>
      <app-theme-switcher></app-theme-switcher>
      <ng-container *ngIf="user; else guestActions">
        <div class="flex items-center gap-3">
          <span *ngIf="displayName" class="hidden text-sm font-semibold text-primary lg:inline">{{ displayName }}</span>
          <button
            type="button"
            (click)="logout()"
            class="rounded-full border border-[var(--card-border)] px-4 py-1.5 text-sm font-medium text-secondary transition hover:border-[var(--accent)] hover:text-accent"
          >
            Logout
          </button>
        </div>
      </ng-container>
      <ng-template #guestActions>
        <div class="flex items-center gap-3">
          <a class="btn-primary" routerLink="/login">Login</a>
          <a
            class="rounded-full border border-[var(--accent)] px-5 py-2 text-sm font-semibold text-accent transition hover:bg-[var(--accent-soft)]"
            routerLink="/register"
          >
            Join Us
          </a>
        </div>
      </ng-template>
    </nav>

    <button
      type="button"
      class="inline-flex items-center justify-center rounded-full bg-[var(--surface-layer)] p-2 text-secondary shadow-md transition hover:shadow-lg md:hidden"
      (click)="toggleOpen()"
    >
      <span class="material-symbols-outlined text-xl">{{ open ? 'close' : 'menu' }}</span>
    </button>
  </div>

  <div *ngIf="open" class="border-t border-[var(--border-contrast)] bg-[var(--surface-layer)] px-4 py-4 backdrop-blur-xl md:hidden">
    <div class="flex flex-col gap-4 text-sm font-semibold text-secondary">
      <a *ngFor="let link of links" routerLink="{{ link.to }}" (click)="toggleOpen()">{{ link.label }}</a>
      <a routerLink="/orders" (click)="toggleOpen()" class="flex items-center gap-2">
        <span class="material-symbols-outlined text-base">shopping_bag</span> Cart ({{ cartCount }})
      </a>
      <div class="border-t border-[var(--border-contrast)] pt-3">
        <app-theme-switcher></app-theme-switcher>
      </div>
      <ng-container *ngIf="user; else mobileGuest">
        <span *ngIf="displayName" class="text-sm text-primary">Signed in as {{ displayName }}</span>
        <button type="button" (click)="logout()" class="text-left text-accent">Logout</button>
      </ng-container>
      <ng-template #mobileGuest>
        <div class="flex flex-col gap-2">
          <a class="btn-primary w-full justify-center" routerLink="/login" (click)="toggleOpen()">Login</a>
          <a
            class="rounded-full border border-[var(--accent)] px-5 py-2 text-center text-sm font-semibold text-accent"
            routerLink="/register"
            (click)="toggleOpen()"
          >
            Join Us
          </a>
        </div>
      </ng-template>
    </div>
  </div>
</header>

// frontend/src/components/Navbar.jsx
import { useState } from 'react';
import { Link, NavLink, useNavigate } from 'react-router-dom';
import { Bars3Icon, XMarkIcon, ShoppingBagIcon } from '@heroicons/react/24/outline';
import { useAuth } from '../context/AuthContext.jsx';
import ThemeSwitcher from './ThemeSwitcher.jsx';
import { useCart } from '../context/CartContext.jsx';

const baseLinks = [
  { to: '/', label: 'Home' },
  { to: '/menu', label: 'Menu' },
  { to: '/orders', label: 'My Orders' },
  { to: '/contact', label: 'Contact' }
];

const Navbar = () => {
  const [open, setOpen] = useState(false);
  const { user, logout } = useAuth();
  const { cartItems } = useCart();
  const navigate = useNavigate();

  const cartCount = cartItems.reduce((sum, item) => sum + item.quantity, 0);
  const displayName = [user?.firstName || user?.firstname, user?.lastName || user?.lastname]
    .filter(Boolean)
    .join(' ')
    .trim() || user?.name || user?.email?.split('@')[0];

  const links = user
    ? [...baseLinks, { to: '/account', label: 'Account' }]
    : baseLinks;

  const handleLogout = () => {
    logout();
    setOpen(false);
    navigate('/');
  };

  return (
    <header className="nav-surface sticky top-0 z-40 shadow-sm">
      <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3">
        <Link to="/" className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-[var(--accent)] text-white shadow-lg">
            <span className="text-lg font-bold">CCD</span>
          </div>
          <span className="brand-title text-lg font-semibold text-primary sm:text-xl">Cafe Coffee Day</span>
        </Link>

        <nav className="hidden items-center gap-6 text-sm font-semibold md:flex">
          {links.map((link) => (
            <NavLink
              key={link.to}
              to={link.to}
              className={({ isActive }) =>
                `text-secondary transition hover:text-accent ${isActive ? 'text-accent' : ''}`
              }
            >
              {link.label}
            </NavLink>
          ))}
          <Link
            to="/orders"
            className="relative inline-flex items-center gap-2 rounded-full border border-[var(--card-border)] bg-[var(--surface-layer)] px-3 py-1.5 text-xs font-semibold text-secondary transition hover:text-accent"
          >
            <ShoppingBagIcon className="h-4 w-4" />
            Cart
            {cartCount > 0 && (
              <span className="absolute -right-2 -top-2 flex h-5 w-5 items-center justify-center rounded-full bg-[var(--accent)] text-xs font-bold text-[var(--accent-contrast)] shadow">
                {cartCount}
              </span>
            )}
          </Link>
          <ThemeSwitcher />
          {user ? (
            <div className="flex items-center gap-3">
              {displayName && (
                <span className="hidden text-sm font-semibold text-primary lg:inline">{displayName}</span>
              )}
              <button
                type="button"
                onClick={handleLogout}
                className="rounded-full border border-[var(--card-border)] px-4 py-1.5 text-sm font-medium text-secondary transition hover:border-[var(--accent)] hover:text-accent"
              >
                Logout
              </button>
            </div>
          ) : (
            <div className="flex items-center gap-3">
              <Link className="btn-primary" to="/login">
                Login
              </Link>
              <Link
                className="rounded-full border border-[var(--accent)] px-5 py-2 text-sm font-semibold text-accent transition hover:bg-[var(--accent-soft)]"
                to="/register"
              >
                Join Us
              </Link>
            </div>
          )}
        </nav>

        <button
          type="button"
          className="inline-flex items-center justify-center rounded-full bg-[var(--surface-layer)] p-2 text-secondary shadow-md transition hover:shadow-lg md:hidden"
          onClick={() => setOpen((prev) => !prev)}
        >
          {open ? <XMarkIcon className="h-6 w-6" /> : <Bars3Icon className="h-6 w-6" />}
        </button>
      </div>

      {open && (
        <div className="border-t border-[var(--border-contrast)] bg-[var(--surface-layer)] px-4 py-4 backdrop-blur-xl md:hidden">
          <div className="flex flex-col gap-4 text-sm font-semibold text-secondary">
            {links.map((link) => (
              <NavLink key={link.to} to={link.to} onClick={() => setOpen(false)}>
                {link.label}
              </NavLink>
            ))}
            <Link to="/orders" onClick={() => setOpen(false)} className="flex items-center gap-2">
              <ShoppingBagIcon className="h-5 w-5" /> Cart ({cartCount})
            </Link>
            <div className="border-t border-[var(--border-contrast)] pt-3">
              <ThemeSwitcher />
            </div>
            {user ? (
              <>
                {displayName && <span className="text-sm text-primary">Signed in as {displayName}</span>}
                <button
                  type="button"
                  onClick={handleLogout}
                  className="text-left text-accent"
                >
                  Logout
                </button>
              </>
            ) : (
              <div className="flex flex-col gap-2">
                <Link className="btn-primary w-full justify-center" to="/login" onClick={() => setOpen(false)}>
                  Login
                </Link>
                <Link
                  className="rounded-full border border-[var(--accent)] px-5 py-2 text-center text-sm font-semibold text-accent"
                  to="/register"
                  onClick={() => setOpen(false)}
                >
                  Join Us
                </Link>
              </div>
            )}
          </div>
        </div>
      )}
    </header>
  );
};

export default Navbar;
