// frontend/src/pages/Login.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import api from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';

const Login = () => {
  const navigate = useNavigate();
  const { login } = useAuth();
  const [form, setForm] = useState({ email: '', password: '' });
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setForm((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setError(null);
    setLoading(true);
    try {
      const { data } = await api.post('/api/auth/login', form);
      login(data);
      navigate('/');
    } catch (err) {
      console.error('Login failed', err);
      setError(err.response?.data?.message || 'Unable to login.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="page-section flex min-h-screen items-center justify-center px-4">
      <div className="card w-full max-w-md">
        <h1 className="text-2xl font-semibold text-primary">Welcome back</h1>
        <p className="mt-2 text-sm text-muted">Sign in to manage orders and explore new flavours.</p>
        <form className="mt-6 space-y-4" onSubmit={handleSubmit}>
          <div>
            <label className="form-label" htmlFor="email">
              Email
            </label>
            <input
              id="email"
              name="email"
              type="email"
              required
              value={form.email}
              onChange={handleChange}
              className="form-input mt-1"
            />
          </div>
          <div>
            <label className="form-label" htmlFor="password">
              Password
            </label>
            <input
              id="password"
              name="password"
              type="password"
              required
              value={form.password}
              onChange={handleChange}
              className="form-input mt-1"
            />
          </div>
          {error && <p className="text-sm text-red-500">{error}</p>}
          <button className="btn-primary w-full" disabled={loading} type="submit">
            {loading ? 'Signing in...' : 'Sign in'}
          </button>
        </form>
        <p className="mt-4 text-center text-sm text-muted">
          New to Cafe Coffee Day?{' '}
          <Link to="/register" className="font-semibold text-accent">
            Create an account
          </Link>
        </p>
      </div>
    </main>
  );
};

export default Login;

// frontend-angular/src/app/pages/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { AuthService, AuthPayload } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './login.component.html'
})
export class LoginComponent {
  private readonly api = inject(ApiService);
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  form = { email: '', password: '' };
  error: string | null = null;
  loading = false;

  async submit(): Promise<void> {
    this.error = null;
    this.loading = true;
    try {
      const payload = await firstValueFrom(
        this.api.post<AuthPayload>('/api/auth/login', this.form)
      );
      this.auth.login(payload);
      this.router.navigate(['/']);
    } catch (err: any) {
      console.error('Login failed', err);
      this.error = err?.error?.message || 'Unable to login.';
    } finally {
      this.loading = false;
    }
  }
}

<main class="page-section flex min-h-screen items-center justify-center px-4">
  <div class="card w-full max-w-md">
    <h1 class="text-2xl font-semibold text-primary">Welcome back</h1>
    <p class="mt-2 text-sm text-muted">Sign in to manage orders and explore new flavours.</p>
    <form class="mt-6 space-y-4" (ngSubmit)="submit()">
      <div>
        <label class="form-label" for="email">Email</label>
        <input
          id="email"
          name="email"
          type="email"
          required
          [(ngModel)]="form.email"
          class="form-input mt-1"
        />
      </div>
      <div>
        <label class="form-label" for="password">Password</label>
        <input
          id="password"
          name="password"
          type="password"
          required
          [(ngModel)]="form.password"
          class="form-input mt-1"
        />
      </div>
      <p *ngIf="error" class="text-sm text-red-500">{{ error }}</p>
      <button class="btn-primary w-full" [disabled]="loading" type="submit">
        {{ loading ? 'Signing in...' : 'Sign in' }}
      </button>
    </form>
    <p class="mt-4 text-center text-sm text-muted">
      New to Cafe Coffee Day?
      <a routerLink="/register" class="font-semibold text-accent">Create an account</a>
    </p>
  </div>
</main>
