// frontend/src/pages/Menu.jsx
const menuItems = [
  {
    name: 'Hazelnut Cappuccino',
    description: 'Classic cappuccino elevated with nutty hazelnut syrup and cocoa dusting.',
    price: '$4.50'
  },
  {
    name: 'Cold Brew Tonic',
    description: 'Slow steeped cold brew over artisanal tonic and citrus peel.',
    price: '$5.80'
  },
  {
    name: 'Rose Pistachio Frappe',
    description: 'Floral rose milk blended with ice, espresso, and crushed pistachio.',
    price: '$6.20'
  },
  {
    name: 'Spiced Masala Chai',
    description: 'Slow simmered spices with Assam tea and creamy milk.',
    price: '$3.80'
  }
];

const Menu = () => (
  <main className="page-section">
    <div className="mx-auto max-w-5xl px-4">
      <header className="text-center">
        <h1 className="section-title">Menu Highlights</h1>
        <p className="section-subtitle">
          Each beverage is thoughtfully crafted with ethically sourced beans and ingredients.
        </p>
      </header>
      <div className="mt-12 grid gap-6 md:grid-cols-2">
        {menuItems.map((item) => (
          <div key={item.name} className="card">
            <h3 className="text-2xl font-semibold text-primary">{item.name}</h3>
            <p className="mt-3 text-sm text-muted">{item.description}</p>
            <p className="mt-4 text-lg font-semibold text-accent">{item.price}</p>
          </div>
        ))}
      </div>
    </div>
  </main>
);

export default Menu;

// frontend-angular/src/app/pages/menu/menu.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

interface MenuItem {
  name: string;
  description: string;
  price: string;
}

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './menu.component.html'
})
export class MenuComponent {
  items: MenuItem[] = [
    {
      name: 'Hazelnut Cappuccino',
      description: 'Classic cappuccino elevated with nutty hazelnut syrup and cocoa dusting.',
      price: '$4.50'
    },
    {
      name: 'Cold Brew Tonic',
      description: 'Slow steeped cold brew over artisanal tonic and citrus peel.',
      price: '$5.80'
    },
    {
      name: 'Rose Pistachio Frappe',
      description: 'Floral rose milk blended with ice, espresso, and crushed pistachio.',
      price: '$6.20'
    },
    {
      name: 'Spiced Masala Chai',
      description: 'Slow simmered spices with Assam tea and creamy milk.',
      price: '$3.80'
    }
  ];
}

<main class="page-section">
  <div class="mx-auto max-w-5xl px-4">
    <header class="text-center">
      <h1 class="section-title">Menu Highlights</h1>
      <p class="section-subtitle">
        Each beverage is thoughtfully crafted with ethically sourced beans and ingredients.
      </p>
    </header>
    <div class="mt-12 grid gap-6 md:grid-cols-2">
      <div *ngFor="let item of items" class="card">
        <h3 class="text-2xl font-semibold text-primary">{{ item.name }}</h3>
        <p class="mt-3 text-sm text-muted">{{ item.description }}</p>
        <p class="mt-4 text-lg font-semibold text-accent">{{ item.price }}</p>
      </div>
    </div>
  </div>
</main>
