// frontend-angular/src/app/pages/admin-dashboard/admin-dashboard.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { AuthService } from '../../services/auth.service';
import { OrdersService, OrderRecord } from '../../services/orders.service';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './admin-dashboard.component.html'
})
export class AdminDashboardComponent implements OnInit {
  readonly auth = inject(AuthService);
  private readonly ordersService = inject(OrdersService);
  private readonly api = inject(ApiService);
  private readonly router = inject(Router);

  orders: OrderRecord[] = [];
  loading = false;
  error: string | null = null;
  updatingId: number | string | null = null;
  readonly orderStatuses = ['placed', 'preparing', 'ready', 'completed', 'cancelled'];

  ngOnInit(): void {
    if (!this.auth.user) {
      this.router.navigate(['/login']);
      return;
    }
    if (this.auth.user.role !== 'admin') {
      this.router.navigate(['/']);
      return;
    }

    this.loading = true;
    this.ordersService.orders$
      .pipe(takeUntilDestroyed())
      .subscribe((records) => {
        this.orders = records;
        this.loading = false;
      });
    this.ordersService.error$
      .pipe(takeUntilDestroyed())
      .subscribe((message) => (this.error = message));
    this.ordersService.fetchOrders(Boolean(this.auth.token));
  }

  async updateStatus(orderId: number | string, status: string): Promise<void> {
    this.updatingId = orderId;
    try {
      const updated = await firstValueFrom(
        this.api.patch<OrderRecord>(`/api/orders/${orderId}/status`, { status })
      );
      this.ordersService.setOrders(
        this.orders.map((order) => (order.id === orderId ? updated : order))
      );
    } catch (err: any) {
      console.error('Failed to update order', err);
      this.error = err?.error?.message || 'Unable to update order status.';
    } finally {
      this.updatingId = null;
    }
  }

  formatItems(order: OrderRecord): string {
    if (Array.isArray(order.items)) {
      return order.items.map((item) => item.name).join(', ');
    }
    try {
      const parsed = JSON.parse(order.items as unknown as string) as { name: string }[];
      return parsed.map((item) => item.name).join(', ');
    } catch {
      return String(order.items);
    }
  }

  totalFor(order: OrderRecord): string {
    const total = Number(order.total_price || order.totalPrice || 0);
    return total.toFixed(2);
  }

  createdAt(order: OrderRecord): string {
    return new Date(order.created_at || order.createdAt || '').toLocaleString();
  }
}

<main class="page-section" *ngIf="auth.user?.role === 'admin'; else redirecting">
  <div class="mx-auto max-w-6xl px-4">
    <header class="mb-10 text-center">
      <h1 class="section-title">Admin control centre</h1>
      <p class="section-subtitle">
        Monitor live orders across all customers and update statuses in real time.
      </p>
    </header>

    <p *ngIf="loading" class="text-sm text-muted">Loading orders...</p>
    <p *ngIf="error" class="text-sm text-red-500">{{ error }}</p>

    <div class="mt-6 grid gap-4">
      <div *ngFor="let order of orders" class="card space-y-4">
        <div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <p class="text-sm font-semibold text-primary">Order #{{ order.id }}</p>
            <p class="text-sm text-muted">Customer: {{ order.customer_name || order.customerId }}</p>
            <p class="text-sm text-muted">{{ formatItems(order) }}</p>
          </div>
          <div class="text-right text-sm text-muted">
            <p class="font-semibold text-accent">${{ totalFor(order) }}</p>
            <p>Placed {{ createdAt(order) }}</p>
          </div>
        </div>
        <div class="flex flex-wrap items-center gap-3">
          <button
            *ngFor="let status of orderStatuses"
            type="button"
            (click)="updateStatus(order.id, status)"
            [disabled]="updatingId === order.id"
            class="rounded-full border px-4 py-1.5 text-sm font-medium transition"
            [ngClass]="order.status === status
              ? 'border-[var(--accent)] bg-[var(--accent)] text-[var(--accent-contrast)]'
              : 'border-[var(--card-border)] bg-[var(--surface-layer)] text-secondary hover:border-[var(--accent)] hover:text-accent'"
          >
            {{ status }}
          </button>
        </div>
      </div>
      <p *ngIf="!loading && orders.length === 0" class="text-sm text-muted">No orders found yet. Encourage customers to place new orders.</p>
    </div>
  </div>
</main>
<ng-template #redirecting>
  <main class="page-section">
    <div class="mx-auto max-w-3xl px-4">
      <p class="text-sm text-muted">Redirecting...</p>
    </div>
  </main>
</ng-template>

// frontend/src/pages/AdminDashboard.jsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';
import useOrders from '../hooks/useOrders.js';

const orderStatuses = ['placed', 'preparing', 'ready', 'completed', 'cancelled'];

const AdminDashboard = () => {
  const { user, token } = useAuth();
  const navigate = useNavigate();
  const { orders, loading, error, setOrders } = useOrders(Boolean(token));
  const [updatingId, setUpdatingId] = useState(null);

  useEffect(() => {
    if (!user) {
      navigate('/login');
    } else if (user.role !== 'admin') {
      navigate('/');
    }
  }, [user, navigate]);

  const updateStatus = async (orderId, status) => {
    setUpdatingId(orderId);
    try {
      const { data } = await api.patch(`/api/orders/${orderId}/status`, { status });
      setOrders((prev) => prev.map((order) => (order.id === orderId ? data : order)));
    } catch (err) {
      console.error('Failed to update order', err);
      alert(err.response?.data?.message || 'Unable to update order status.');
    } finally {
      setUpdatingId(null);
    }
  };

  if (!user || user.role !== 'admin') {
    return null;
  }

  return (
    <main className="page-section">
      <div className="mx-auto max-w-6xl px-4">
        <header className="mb-10 text-center">
          <h1 className="section-title">Admin control centre</h1>
          <p className="section-subtitle">
            Monitor live orders across all customers and update statuses in real time.
          </p>
        </header>

        {loading && <p className="text-sm text-muted">Loading orders...</p>}
        {error && <p className="text-sm text-red-500">{error}</p>}

        <div className="mt-6 grid gap-4">
          {orders.map((order) => (
            <div key={order.id} className="card space-y-4">
              <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                <div>
                  <p className="text-sm font-semibold text-primary">Order #{order.id}</p>
                  <p className="text-sm text-muted">Customer: {order.customer_name || order.customerId}</p>
                  <p className="text-sm text-muted">
                    {Array.isArray(order.items)
                      ? order.items.map((item) => item.name).join(', ')
                      : (() => {
                          try {
                            return JSON.parse(order.items).map((item) => item.name).join(', ');
                          } catch (e) {
                            return order.items;
                          }
                        })()}
                  </p>
                </div>
                <div className="text-right text-sm text-muted">
                  <p className="font-semibold text-accent">${Number(order.total_price || order.totalPrice).toFixed(2)}</p>
                  <p>Placed {new Date(order.created_at || order.createdAt).toLocaleString()}</p>
                </div>
              </div>
              <div className="flex flex-wrap items-center gap-3">
                {orderStatuses.map((status) => (
                  <button
                    key={status}
                    type="button"
                    onClick={() => updateStatus(order.id, status)}
                    disabled={updatingId === order.id}
                    className={`rounded-full border px-4 py-1.5 text-sm font-medium transition ${
                      order.status === status
                        ? 'border-[var(--accent)] bg-[var(--accent)] text-[var(--accent-contrast)]'
                        : 'border-[var(--card-border)] bg-[var(--surface-layer)] text-secondary hover:border-[var(--accent)] hover:text-accent'
                    }`}
                  >
                    {status}
                  </button>
                ))}
              </div>
            </div>
          ))}
          {!loading && orders.length === 0 && (
            <p className="text-sm text-muted">No orders found yet. Encourage customers to place new orders.</p>
          )}
        </div>
      </div>
    </main>
  );
};

export default AdminDashboard;
